apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.global.secrets.dbRootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.global.secrets.dbUser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.global.secrets.dbPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.global.secrets.dbName | b64enc | quote }}