# app-chart/charts/backend/templates/secret.yaml (VERSÃO CORRIGIDA)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
data:
  # Este secret é para o JWT.
  # A correção está aqui: usamos '.Values.global' para aceder
  # aos valores do chart pai.
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret | b64enc | quote }}