# app-chart/values.yaml (VERSÃO CORRIGIDA)

# Configurações específicas para cada subchart
frontend:
  image:
    repository: lgstavo/frontend
    tag: "1.0.3" # Use a sua última tag funcional

backend:
  image:
    repository: lgstavo/backend
    tag: "1.0.2" # Use a sua última tag funcional

db:
  image:
    repository: lgstavo/db
    tag: "1.0.0"

# Configurações do Ingress (permanece no nível superior)
ingress:
  enabled: true
  className: "nginx"
  host: k8s.local

global:
  secrets:
    dbRootPassword: "root_password_super_secreta"
    dbUser: "user_app"
    dbPassword: "user_password_secreta"
    dbName: "amizade_db"
    jwtSecret: "a2c4e6858c1b4e29a3f2d8e5g1h3i5j7k9l2m4n6o8p1q3r5s7t9u1v3w5x7y9z0a2b4"