apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.dbName | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}